name: deploy on server and setup env
on: [push]
jobs:
  build:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Yarn setup with cache
        uses: DerYeger/yarn-setup-action@master
        with:
          node-version: 16.13.0
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_BAR: ${{ secrets.BAR }}
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: '-rltgoDzvO --delete'
          SOURCE: ''
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
          EXCLUDE: '/dist/, /node_modules/'
